package cat.subi.itaca.nutrition.application

import cat.subi.itaca.nutrition.adapter.out.persistence.MealEntity
import cat.subi.itaca.nutrition.adapter.out.persistence.MealRepository
import cat.subi.itaca.nutrition.domain.MealType
import cat.subi.itaca.shared.chat.ChatTools
import org.springframework.ai.tool.annotation.Tool
import org.springframework.ai.tool.annotation.ToolParam
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.LocalDate

data class MealDto(
    val id: Long,
    val date: String,
    val mealType: String,
    val description: String,
    val onPlan: Boolean?,
    val calories: Int?,
    val notes: String?,
)

/** Claude's read of a meal photo — a proposal the user reviews before it is saved. */
data class MealAnalysis(
    val description: String,
    val calories: Int?,
    val mealType: String,
    val onPlan: Boolean,
)

data class MealResult(
    val saved: Boolean,
    val meal: MealDto? = null,
    val error: String? = null,
)

/** Recent meals plus the anti-inflammatory paleo adherence over the window. */
data class MealsSummary(
    val meals: List<MealDto>,
    val total: Int,
    val onPlan: Int,
)

/** A meal to record (shared by the chat tool and the REST form). */
data class MealCommand(
    val date: LocalDate,
    val mealType: String,
    val description: String,
    val onPlan: Boolean? = null,
    val calories: Int? = null,
    val notes: String? = null,
)

/** Port: analyses a meal photo and proposes its description, calories, type and adherence. */
fun interface MealPhotoAnalyzer {
    fun analyze(
        image: ByteArray,
        mimeType: String,
    ): MealAnalysis
}

/**
 * Application service of the nutrition context, exposed to the chat as tools and reused
 * by the REST adapter. Records and retrieves meals only; the meal proposals themselves are
 * generated by the model from the prompt (training- and flare-aware), not here.
 */
@Service
class NutritionService(
    private val meals: MealRepository,
    private val photoAnalyzer: MealPhotoAnalyzer,
) : ChatTools {
    @Tool(
        name = "log_meal",
        description =
            "Logs a meal Oriol ate. mealType is breakfast, lunch, dinner or snack. description is what he " +
                "ate (free text). onPlan: whether it fits the anti-inflammatory paleo plan — set it from your " +
                "judgement of the description. Date defaults to today.",
    )
    @Transactional
    fun logMeal(
        @ToolParam(description = "Meal type: breakfast, lunch, dinner or snack") mealType: String,
        @ToolParam(description = "What was eaten (free text)") description: String,
        @ToolParam(description = "Whether it fits the anti-inflammatory paleo plan", required = false) onPlan: Boolean?,
        @ToolParam(description = "Estimated calories (kcal), if known", required = false) calories: Int?,
        @ToolParam(description = "Date YYYY-MM-DD; omit for today", required = false) date: String?,
        @ToolParam(description = "Free-text notes", required = false) notes: String?,
    ): MealResult =
        runCatching {
            val meal =
                save(
                    MealCommand(
                        date = date?.let(LocalDate::parse) ?: LocalDate.now(),
                        mealType = mealType,
                        description = description,
                        onPlan = onPlan,
                        calories = calories,
                        notes = notes,
                    ),
                )
            MealResult(saved = true, meal = meal)
        }.getOrElse { MealResult(saved = false, error = it.message) }

    /** Analyses a meal photo into a proposal; the caller reviews it before saving via [save]. */
    fun analyzePhoto(
        image: ByteArray,
        mimeType: String,
    ): MealAnalysis = photoAnalyzer.analyze(image, mimeType)

    @Tool(
        name = "query_meals",
        description =
            "Returns the meals logged in the last days (default 7) with the anti-inflammatory paleo adherence " +
                "(how many were on-plan). Use it to see eating patterns and adherence.",
    )
    fun queryMeals(
        @ToolParam(description = "How many days back to look (default 7)", required = false) days: Int?,
    ): MealsSummary = recent(days ?: DEFAULT_QUERY_DAYS)

    /** Records a meal; validates the meal type and stores its canonical wire form. */
    @Transactional
    fun save(command: MealCommand): MealDto {
        val type = MealType.from(command.mealType)
        require(command.description.isNotBlank()) { "description cannot be blank" }
        val saved =
            meals.save(
                MealEntity(
                    date = command.date,
                    mealType = type.wire,
                    description = command.description.trim(),
                    onPlan = command.onPlan,
                    calories = command.calories,
                    notes = command.notes?.takeIf { it.isNotBlank() },
                ),
            )
        return saved.toDto()
    }

    fun recent(days: Int): MealsSummary {
        val rows = meals.findByDateGreaterThanEqualOrderByDateDescIdDesc(LocalDate.now().minusDays(days.toLong()))
        return MealsSummary(
            meals = rows.map { it.toDto() },
            total = rows.size,
            onPlan = rows.count { it.onPlan == true },
        )
    }

    @Transactional
    fun delete(id: Long) {
        if (!meals.existsById(id)) throw NoSuchElementException("Meal $id not found")
        meals.deleteById(id)
    }

    private fun MealEntity.toDto() = MealDto(id!!, date.toString(), mealType, description, onPlan, calories, notes)

    private companion object {
        const val DEFAULT_QUERY_DAYS = 7
    }
}
