/**
 * Nutrition bounded context: meals logged by the user, with anti-inflammatory
 * paleo adherence. Training- and flare-aware meal proposals are generated by the
 * chat model from the prompt; this context only records and retrieves meals.
 */
@org.springframework.modulith.ApplicationModule(displayName = "Nutrition")
package cat.subi.itaca.nutrition;
